// This file was auto-generated by ML.NET Model Builder.

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using PassportRecognizerML.Model;

namespace PassportRecognizerML.ConsoleApp
{
    internal class Program
    {
        //Dataset to use for predictions
        private const string DATA_FILEPATH = @"C:\repo\my\PassportRecognizer\DatasetGenerator\bin\Debug\netcoreapp2.2\dataset.csv";

        private static void Main(string[] args)
        {
            ModelBuilder.CreateModel();

            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Number with predicted Number from sample data...\n\n");
            Console.WriteLine($"\n\nActual Number: {sampleData.Number} \nPredicted Number value {predictionResult.Prediction} \nPredicted Number scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data

        #region CreateSingleDataSample

        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: false,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }

        #endregion CreateSingleDataSample
    }
}